/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.javeriana.personapp.view;

import co.edu.javeriana.personapp.model.dto.PersonaDTO;
import co.edu.javeriana.personapp.model.dto.TelefonoDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esteb
 */
public class TelefonoPanel extends javax.swing.JPanel {

    /**
     * Creates new form TelefonoPanel
     */
    
    private Principal principal;
    
    public TelefonoPanel(Principal principal) {
        initComponents();
        this.principal = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        titulo = new javax.swing.JLabel();
        botInsertar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botRefres = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botCont = new javax.swing.JButton();
        cajaNumero = new javax.swing.JTextField();
        botMod = new javax.swing.JButton();
        cajaOperador = new javax.swing.JTextField();
        botElim = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTelefonos = new javax.swing.JTable();
        botIrPer = new javax.swing.JButton();
        botSalir2 = new javax.swing.JButton();
        cmbDuenios = new javax.swing.JComboBox<>();
        txtContar = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel6.setText("Telefonos:");

        titulo.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 153, 153));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        titulo.setText("PERSONAPP");

        botInsertar.setBackground(new java.awt.Color(255, 255, 204));
        botInsertar.setText("Insertar");
        botInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInsertarActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero");

        botBuscar.setBackground(new java.awt.Color(255, 255, 204));
        botBuscar.setText("Buscar");
        botBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Operador");

        botRefres.setBackground(new java.awt.Color(255, 255, 204));
        botRefres.setText("Refrescar");
        botRefres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRefresActionPerformed(evt);
            }
        });

        jLabel5.setText("Dueño");

        botCont.setBackground(new java.awt.Color(255, 255, 204));
        botCont.setText("Contar");
        botCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botContActionPerformed(evt);
            }
        });

        botMod.setBackground(new java.awt.Color(255, 255, 204));
        botMod.setText("Modificar");
        botMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botModActionPerformed(evt);
            }
        });

        botElim.setBackground(new java.awt.Color(255, 255, 204));
        botElim.setText("Eliminar");
        botElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botElimActionPerformed(evt);
            }
        });

        tablaTelefonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero", "Operador", "Dueño"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTelefonos);

        botIrPer.setBackground(new java.awt.Color(204, 255, 255));
        botIrPer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botIrPer.setText("Ir a Personas");
        botIrPer.setToolTipText("");
        botIrPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botIrPerActionPerformed(evt);
            }
        });

        botSalir2.setBackground(new java.awt.Color(204, 255, 255));
        botSalir2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botSalir2.setText("Salir");
        botSalir2.setToolTipText("");
        botSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalir2ActionPerformed(evt);
            }
        });

        cmbDuenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDueniosActionPerformed(evt);
            }
        });

        txtContar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(cajaOperador, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(cmbDuenios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContar))
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botInsertar)
                            .addGap(18, 18, 18)
                            .addComponent(botBuscar)
                            .addGap(18, 18, 18)
                            .addComponent(botRefres)
                            .addGap(18, 18, 18)
                            .addComponent(botCont)
                            .addGap(18, 18, 18)
                            .addComponent(botMod)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botElim)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botIrPer, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtContar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cajaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDuenios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botInsertar)
                    .addComponent(botBuscar)
                    .addComponent(botRefres)
                    .addComponent(botCont)
                    .addComponent(botMod)
                    .addComponent(botElim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botIrPer)
                .addGap(18, 18, 18)
                .addComponent(botSalir2)
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInsertarActionPerformed
        if(cajaNumero.getText().equals("")) JOptionPane.showMessageDialog(null, "El campo de numero nunca puede estar vacio");
        String celDuenio = cmbDuenios.getSelectedItem().toString().split(" ")[0];
        System.out.println(celDuenio);
        Boolean creado = this.principal.crearTelefono(cajaNumero.getText(), cajaOperador.getText(), celDuenio);
        
        if(creado) JOptionPane.showMessageDialog(null, "Telefono registrado con exito!");
        else JOptionPane.showMessageDialog(null, "No se pudo registrar el telefono. Verifique que no dejo ningun campo en blanco");
    }//GEN-LAST:event_botInsertarActionPerformed

    private void botBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBuscarActionPerformed
        
        List<TelefonoDTO> telefonos = new ArrayList<>();
        String celDuenio = cmbDuenios.getSelectedItem().toString().split(" ")[0];
        if(cajaNumero.getText().equals("")) telefonos = this.principal.findByDuenioTelefonos(celDuenio);
        else telefonos.add(this.principal.findByIdTelefonos(cajaNumero.getText()));

        DefaultTableModel model = (DefaultTableModel) tablaTelefonos.getModel();

        int filas = tablaTelefonos.getRowCount();
        for (int i = 0;filas>i; i++) model.removeRow(0);
        
        if(telefonos == null) JOptionPane.showMessageDialog(null, "Esta persona no tiene telefonos registrados");
        if(telefonos.get(0) == null) JOptionPane.showMessageDialog(null, "El telefono no esta registrado");
        else for(TelefonoDTO t : telefonos) model.addRow(new Object[]{t.getNumero(), t.getOperador(), t.getDuenio()});
    }//GEN-LAST:event_botBuscarActionPerformed

    private void botRefresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRefresActionPerformed
        refrescar();
    }//GEN-LAST:event_botRefresActionPerformed

    private void botContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botContActionPerformed
        Integer cant = this.principal.contarTelefonos();
        txtContar.setText(""+cant);
        JOptionPane.showMessageDialog(null, "Cantidad de telefonos: " + cant);
    }//GEN-LAST:event_botContActionPerformed

    private void botModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botModActionPerformed
        if(cajaNumero.getText().equals("")) JOptionPane.showMessageDialog(null, "El campo de numero nunca puede estar vacio");
        String celDuenio = cmbDuenios.getSelectedItem().toString().split(" ")[0];
        Boolean editado = this.principal.editarTelefono(cajaNumero.getText(), cajaOperador.getText(), celDuenio);
        
        if(editado) JOptionPane.showMessageDialog(null, "Telefono editado con exito!");
        else JOptionPane.showMessageDialog(null, "No se pudo editar el telefono. Verifique que el numero este registrado");
    }//GEN-LAST:event_botModActionPerformed

    private void botElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botElimActionPerformed
        Boolean eliminado = this.principal.eliminarTelefono(cajaNumero.getText());

        //Ventana emergente
        if(eliminado) JOptionPane.showMessageDialog(null, "Telefono Eliminado con exito!");
        else JOptionPane.showMessageDialog(null, "No se pudo eliminar el telefono. Verifique que el numero este bien ingresado o que el telefono existe en el sistema");
    }//GEN-LAST:event_botElimActionPerformed

    private void botIrPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botIrPerActionPerformed
        this.principal.irTelefonoPersona();
    }//GEN-LAST:event_botIrPerActionPerformed

    private void botSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalir2ActionPerformed
        this.principal.salir();
    }//GEN-LAST:event_botSalir2ActionPerformed

    private void cmbDueniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDueniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDueniosActionPerformed

    protected void agregarDuenios(List<PersonaDTO> duenios)
    {
        for(PersonaDTO p : duenios) cmbDuenios.addItem(p.toString());
    }
    
    protected void refrescar()
    {
        List<TelefonoDTO> telefonos = this.principal.findAllTelefonos();

        DefaultTableModel model = (DefaultTableModel) tablaTelefonos.getModel();

        int filas = tablaTelefonos.getRowCount();
        for (int i = 0;filas>i; i++) model.removeRow(0);

        if(telefonos != null) for(TelefonoDTO t : telefonos) model.addRow(new Object[]{t.getNumero(), t.getOperador(), t.getDuenio()});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botBuscar;
    private javax.swing.JButton botCont;
    private javax.swing.JButton botElim;
    private javax.swing.JButton botInsertar;
    private javax.swing.JButton botIrPer;
    private javax.swing.JButton botMod;
    private javax.swing.JButton botRefres;
    private javax.swing.JButton botSalir2;
    private javax.swing.JTextField cajaNumero;
    private javax.swing.JTextField cajaOperador;
    private javax.swing.JComboBox<String> cmbDuenios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tablaTelefonos;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtContar;
    // End of variables declaration//GEN-END:variables
}
